/**
 * Migration objects available for the Staging Table approach.
 * Source: SAP Help Portal, "Available Migration Objects" (SAP S/4HANA on-premise),
 * filtered to Migration Approach = "Staging Table". 228 objects.
 *
 * Format: [name, businessObjectType, customFieldSupport, component]
 *   businessObjectType: M = Master data, T = Transactional data
 *   customFieldSupport: Y = Yes, N = Not applicable
 */
const RAW = [
  ['AVC - Characteristics group','M','N','LO-VCH'],
  ['AVC - Configuration profile (restricted)','M','N','LO-VCH'],
  ['AVC - Material variant','M','N','LO-VCH'],
  ['Bank','M','N','FI'],
  ['Batch unique at material and client level','M','N','LO-BM'],
  ['Batch unique at plant level','M','N','LO-BM'],
  ['Change request and activity for SAP Management of Change','T','N','CA-IAM-MOC'],
  ['Characteristic','M','N','CA-CL'],
  ['Class','M','N','N'],
  ['Class hierarchy','T','N','CA-CL'],
  ['CO - Activity type','M','N','CO'],
  ['CO - Business process','M','N','CO-OM'],
  ['CO - Cost center','M','N','CO'],
  ['CO - Cost rate','M','N','CO'],
  ['CO - Internal order (restricted)','T','N','CO'],
  ['CO - Profit center','M','N','CO'],
  ['CO - Statistical key figure','M','N','CO'],
  ['Condition contract','T','N','LO-AB'],
  ['Condition record for batch determination (for all areas)','M','N','LO-BM'],
  ['Condition record for pricing (general template)','M','N','SD'],
  ['Condition record for pricing in purchasing (restricted)','M','N','MM-PUR'],
  ['Condition record for pricing in sales (restricted)','M','N','SD'],
  ['Consent','T','N','CA-GTF-CON'],
  ['Customer','M','Y','SD'],
  ['Customer - extend existing record by credit management data','M','N','SD'],
  ['Customer - extend existing record by multiple addresses','M','N','SD'],
  ['Customer - extend existing record by new org levels','M','Y','SD'],
  ['Customer - extend existing record by Thailand branch code','M','N','SD'],
  ['DG - Assessment for packaged product','M','N','EHS-SUS-DG'],
  ['DG - Assessment for unpackaged product (content-based)','M','N','EHS-SUS-DG'],
  ['DG - Assessment for unpackaged product (text-based)','M','N','EHS-SUS-DG'],
  ['DG - Technical names for substance','M','N','EHS-SUS-DG'],
  ['Document info record','M','N','CA-DMS'],
  ['ECM - Change master','M','N','PLM-WUI-OBJ-ECN'],
  ['EFD - Reinf report (Brazil)','T','N','FI-LOC-FI'],
  ['EHS - Calculation definition','M','N','EHS-SUS-EM'],
  ['EHS - Chemical/Physical property','M','N','EHS-SUS-FND'],
  ['EHS - Compliance requirement','M','N','EHS-SUS-CI'],
  ['EHS - Compliance scenario','M','N','EHS-SUS-EM'],
  ['EHS - Data classifier','M','N','EHS-SUS-EM'],
  ['EHS - Data collection','M','N','EHS-SUS-EM'],
  ['EHS - Deviation incident','M','N','EHS-SUS-IM'],
  ['EHS - Incident','T','N','EHS-SUS-IM'],
  ['EHS - Location','M','N','EHS-SUS-FND'],
  ['EHS - Location aggregation','M','N','EHS-SUS-EM'],
  ['EHS - Location classifier','M','N','EHS-SUS-CI'],
  ['EHS - Location hierarchy','M','N','EHS-SUS-FND'],
  ['EHS - Task','T','N','EHS-SUS-EM'],
  ['Exchange rate','M','N','FI'],
  ['FI - Accounts payable open item','T','N','FI-AP'],
  ['FI - Accounts receivable open item','T','N','FI-AR'],
  ['FI - Bank account balance (deprecated)','T','N','FIN-FSCM-CLM'],
  ['FI - Cash memo record','T','N','FIN-FSCM-CLM'],
  ['FI - G/L account','M','N','FI'],
  ['FI - G/L account - extend existing record by new org levels','M','N','FI'],
  ['FI - G/L account balance and open/line item','T','Y','FI'],
  ['FI - Historical balance','T','N','FI'],
  ['FI - SEPA mandate','M','N','FI'],
  ['FI-CA - Direct debit mandate','M','N','FI'],
  ['Field Logistics - Container (restricted)','M','Y','CA-FL-SG'],
  ['Field logistics - Supplier item','T','Y','CA-FL-SRV'],
  ['Fixed asset - Master data','M','Y','FI-AA'],
  ['Fixed asset - Postings','T','N','FI-AA'],
  ['Fixed asset - Usage object','M','N','FI-AA'],
  ['Fixed asset (incl. balances and transactions)','M','N','FI-AA'],
  ['HCM - Employee','M','N','PA-PA-XX-MIG'],
  ['HCM - Object','M','N','PA-PA-XX-MIG'],
  ['HCM - Relationship','M','N','PA-PA-XX-MIG'],
  ['JIT - Communication group','M','N','LE-JIT-S2P'],
  ['JIT - Control cycle','M','Y','LE-JIT-S2P'],
  ['JIT - Customer','M','N','LE-JIT-S2C'],
  ['JIT - Packing group specification','M','N','LE-JIT-S2C'],
  ['JIT - Supply control','M','N','LE-JIT-S2C'],
  ['JVA - Cost center suspense','M','N','CA-JVA'],
  ['JVA - Joint operating agreement','M','N','CA-JVA'],
  ['JVA - Joint venture master data (deprecated)','M','N','CA-JVA'],
  ['JVA - Joint venture partner','M','N','CA-JVA'],
  ['JVA - Project suspense','M','N','CA-JVA'],
  ['JVA - Venture suspense','M','N','CA-JVA'],
  ['Legal document','T','Y','CM-GF'],
  ['Legal transaction','T','Y','CM-GF'],
  ['LO - Handling unit','T','N','LO-HU-BF'],
  ['Master recipe','M','N','PP-PI'],
  ['Material - Forecast planning','M','N','MM'],
  ['Material BOM','M','N','PP-BD'],
  ['Material inventory balance','T','N','MM-IM'],
  ['Material listing and exclusion','M','N','SD'],
  ['MM - Model product specification','M','N','MM-PUR-MPS'],
  ['MM - Purchase contract','T','N','MM-PUR'],
  ['MM - Purchase order (only open PO)','T','Y','MM-PUR'],
  ['MM - Purchase scheduling agreement','T','N','MM-PUR'],
  ['MM - Purchasing info record with conditions','M','N','MM-PUR'],
  ['MM - Purchasing info record- extend existing record','M','N','MM-PUR'],
  ['MM - Source list','T','N','MM-PUR'],
  ['Object classification - Code group (QPGR)','M','N','CA-CL'],
  ['Object classification - Document (DRAW)','M','N','CA-CL'],
  ['Object classification - General template','M','N','CA-CL'],
  ['Object classification - Inspection characteristic (QPMK)','M','N','CA-CL'],
  ['Object classification - Inspection method (QMTB)','M','N','CA-CL'],
  ['Object classification - Material (MARA)','M','N','CA-CL'],
  ['Object classification - Purchasing info record (EINA)','M','N','CA-CL'],
  ['Object classification - Selected set (QPAM)','M','N','CA-CL'],
  ['PC - Analytical composition','M','N','EHS-SUS-FND'],
  ['PC - Confidential business information','M','N','EHS-SUS-FND'],
  ['PC - Material-based composition','M','N','EHS-SUS-FND'],
  ['PC - Physical-chemical property','M','N','EHS-SUS-FND'],
  ['PC - Polymer composition','M','N','EHS-SUS-FND'],
  ['PC - Product compliance info','M','N','EHS-SUS-FND'],
  ['PC - Raw material compliance info','M','N','EHS-SUS-FND'],
  ['PC - Safety-related property','M','N','EHS-SUS-FND'],
  ['PC - Substance','M','N','EHS-SUS-FND'],
  ['PM - Equipment','M','Y','PM'],
  ['PM - Equipment BOM','M','N','PM'],
  ['PM - Equipment task list','M','N','PM'],
  ['PM - Functional location','M','Y','PM'],
  ['PM - Functional location BOM','M','N','PM'],
  ['PM - Functional location task list','M','N','PM'],
  ['PM - General maintenance task list','M','N','PM'],
  ['PM - Maintenance item','M','Y','PM'],
  ['PM - Maintenance notification','M','Y','PM'],
  ['PM - Maintenance order','T','Y','PM'],
  ['PM - Maintenance plan','M','Y','PM'],
  ['PM - Measurement document','M','N','PM'],
  ['PM - Measuring point','M','N','PM'],
  ['PMA - Customer compliance assessment','M','N','EHS-SUS-PMA'],
  ['PMA - Simple compliance assessment','M','N','EHS-SUS-PMA'],
  ['PMA - Supplier information assessment','M','N','EHS-SUS-PMA'],
  ['PP - Process order (only open PO)','T','N','PP-PI-POR'],
  ['PP - Production order (only open PO)','T','N','PP-SFC'],
  ['PP-KAB - Kanban control cycle','M','N','PP-KAB'],
  ['PP-KAB - Production supply area','M','Y','PP-KAB'],
  ['PRA - Account entry control','M','N','IS-OIL-PRA'],
  ['PRA - Allocation cross reference','M','N','IS-OIL-PRA'],
  ['PRA - Check input process rule','M','N','IS-OIL-PRA'],
  ['PRA - Check input translation','M','N','IS-OIL-PRA'],
  ['PRA - Chemical analysis data','M','N','IS-OIL-PRA'],
  ['PRA - Contract','M','N','IS-OIL-PRA'],
  ['PRA - Contract volume','T','N','IS-OIL-PRA'],
  ['PRA - Delivery network','M','N','IS-OIL-PRA'],
  ['PRA - Delivery network allocation profile','M','N','IS-OIL-PRA'],
  ['PRA - Delivery network downstream node','M','N','IS-OIL-PRA'],
  ['PRA - Division order interest','M','N','IS-OIL-PRA'],
  ['PRA - DOI accounting','M','N','IS-OIL-PRA'],
  ['PRA - DOI MP WC cross reference','M','N','IS-OIL-PRA'],
  ['PRA - extend existing customer by PRA data','M','N','IS-OIL-PRA'],
  ['PRA - extend existing supplier by PRA data','M','N','IS-OIL-PRA'],
  ['PRA - Joint venture','M','N','IS-OIL-PRA'],
  ['PRA - Journal entry open balance','T','N','IS-OIL-PRA'],
  ['PRA - Marketing group assignment','M','N','IS-OIL-PRA'],
  ['PRA - Measurement point','M','N','IS-OIL-PRA'],
  ['PRA - Measurement point allocation profile','M','N','IS-OIL-PRA'],
  ['PRA - Measurement point volume','T','N','IS-OIL-PRA'],
  ['PRA - MP-WC to contract cross reference','M','N','IS-OIL-PRA'],
  ['PRA - MP/WC transporter cross reference','M','N','IS-OIL-PRA'],
  ['PRA - Ownership lease','M','N','IS-OIL-PRA'],
  ['PRA - Remitter to DOI cross reference','M','N','IS-OIL-PRA'],
  ['PRA - Settlement diversity','M','N','IS-OIL-PRA'],
  ['PRA - Settlement statement DOI cross reference','M','N','IS-OIL-PRA'],
  ['PRA - State tax rate','M','N','IS-OIL-PRA'],
  ['PRA - Tax calculation data','M','N','IS-OIL-PRA'],
  ['PRA - Unit venture tract','M','N','IS-OIL-PRA'],
  ['PRA - Valuation cross reference','M','N','IS-OIL-PRA'],
  ['PRA - Valuation formula','M','N','IS-OIL-PRA'],
  ['PRA - WC/DN theoretical calculation method','M','N','IS-OIL-PRA'],
  ['PRA - Well and well completion','M','N','IS-OIL-PRA'],
  ['PRA - Well completion tax classification','M','N','IS-OIL-PRA'],
  ['PRA - Well completion test','M','N','IS-OIL-PRA'],
  ['PRA - Well completion volume','T','N','IS-OIL-PRA'],
  ['Product','M','Y','LO'],
  ['Product - extend existing record by new org levels','M','Y','LO'],
  ['Product - extend existing record with long text','M','N','LO'],
  ['Product classification - Commodity code','M','N','FT-ITR-CLS'],
  ['Product classification - Legal control','M','N','FT-ITR-CLS'],
  ['Product consumption','M','N','MM'],
  ['Production version','M','N','PP'],
  ['PS - Network','T','N','PS'],
  ['PS - Project','T','N','PS'],
  ['PS - WBS element','T','N','PS'],
  ['QM - Inspection method','M','N','QM'],
  ['QM - Inspection plan','M','N','QM'],
  ['QM - Master inspection characteristic','M','N','QM'],
  ['QM - Quality info record','M','N','QM'],
  ['QM - Selected set','M','N','QM'],
  ['QM - Selected set code','M','N','QM'],
  ['QM/PM - Catalog code group/code','M','N','QM'],
  ['Real estate - Occupancy group','M','Y','RE-FX'],
  ['Real estate - Usage enablement group','M','Y','RE-FX'],
  ['Real estate contract','T','Y','RE-FX'],
  ['Revenue accounting contract','T','N','FI-RA'],
  ['RFM - Assortment module','M','N','LO-RFM-MD-LST'],
  ['RFM - MCHN Characteristic value restriction','M','N','LO-RFM-MD-MC'],
  ['RFM - Merchandise category','M','N','LO-RFM-MD-MC'],
  ['RFM - Merchandise category characteristic value restriction','M','N','LO-RFM-MD-MC'],
  ['RFM - Merchandise category hierarchy node','M','N','LO-RFM-MD-MC'],
  ['RFM - Merchandise category hierarchy node assignment','M','N','LO-RFM-MD-MC'],
  ['RFM - Merchandise category reference article','M','N','LO-RFM-MD-MC'],
  ['RFM - Product assignment to distribution center','M','N','LO-RFM-MD-LST'],
  ['Routing','M','N','PP'],
  ['SD - Condition record for free goods','M','N','SD'],
  ['SD - Condition Record for Material determination','M','N','SD'],
  ['SD - Customer Material','M','Y','SD'],
  ['SD - Sales contract','T','N','SD'],
  ['SD - Sales order (only open SO)','T','Y','SD'],
  ['SD - Sales scheduling agreement','T','N','SD-SLS'],
  ['SDS - Assessment for unpackaged product','M','N','EHS-SUS-SDS'],
  ['SDS - Shipment history','T','N','EHS-SUS-SDS'],
  ['Service order (only open SRVO)','T','Y','CRM-S4-SRV-SVO'],
  ['Service product','M','Y','LO'],
  ['Software/Hardware constraint','T','N','PLM-ESD-ESC'],
  ['Supplier','M','Y','MM'],
  ['Supplier - extend existing record by multiple addresses','M','N','MM'],
  ['Supplier - extend existing record by new org levels','M','Y','MM'],
  ['Supplier - extend existing record by Thailand branch code','M','N','MM'],
  ['TRM - Commercial paper','T','N','FIN-FSCM-TRM-TM'],
  ['TRM - Deposit at notice','T','N','FIN-FSCM-TRM-TM'],
  ['TRM - Foreign exchange collar - contract','T','N','FIN-FSCM-TRM'],
  ['TRM - Foreign exchange spot/forward transaction - contract','T','N','FIN-FSCM-TRM-TM'],
  ['TRM - Foreign exchange swap - contract','T','N','FIN-FSCM-TRM-TM'],
  ['TRM - FX option','T','N','FIN-FSCM-TRM-TM'],
  ['TRM - Interest rate instrument','T','N','FIN-FSCM-TRM'],
  ['TRM - Position value','T','N','FIN-FSCM-TRM-TM'],
  ['Warehouse fixed bin assignment','M','N','SCM-EWM'],
  ['Warehouse stock','M','N','SCM-EWM'],
  ['Warehouse stock (deprecated)','M','N','SCM-EWM'],
  ['Warehouse storage bin','M','N','SCM-EWM'],
  ['Warehouse storage bin sorting','M','N','SCM-EWM'],
  ['Warranty claim','T','Y','LO-WTY'],
  ['Work center/Resource','M','N','PP'],
];

const OBJECTS = RAW.map(([name, type, custom, component]) => ({
  name,
  businessObjectType: type === 'M' ? 'Master data' : 'Transactional data',
  customFieldSupport: custom === 'Y',
  component: component === 'N' ? null : component,
  restricted: /\(restricted\)/i.test(name),
  deprecated: /\(deprecated\)/i.test(name),
}));

const BY_NORMALISED = new Map(OBJECTS.map((o) => [normalise(o.name), o]));

function normalise(name) {
  return String(name).toLowerCase().replace(/\s+/g, ' ').trim();
}

/**
 * Template titles carry only the base object name, so a template for
 * "Product" must also match catalog entries like "Product (restricted)".
 */
function findObject(objectName) {
  if (!objectName) return null;
  const key = normalise(objectName);
  const exact = BY_NORMALISED.get(key);
  if (exact) return exact;

  const baseMatches = OBJECTS.filter((o) => normalise(o.name).replace(/\s*\((restricted|deprecated)\)$/, '') === key);
  return baseMatches.length === 1 ? baseMatches[0] : null;
}

module.exports = { OBJECTS, findObject, count: OBJECTS.length };
